# Generated by Django 3.0.7 on 2020-08-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20200821_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='instance_book',
            new_name='instant_book',
        ),
    ]
